apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plant-care-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: plant.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plant-care-service
            port:
              number: 80
